
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: variation_products_development

  
test:
  <<: *default
  database:  variation_products_test


production:
  <<: *default
  database: ecommerce_app_production
  username: ecommerce_app
  password: <%= ENV["ECOMMERCE_APP_DATABASE_PASSWORD"] %>
